// BARBM312 — AI in Investment and Business Growth
// Bachelor · FHEQ Level 6 · 5 ECTS · EU Business School
// Pedagogical architecture modelled on Dr. Haas / MARTI301, applying:
//   - JD Meier "Thumbnail Thinking" (framework galleries / Slibraries)
//   - JD Meier "Council of Giants" (author/thinker Slibrary cards)
//   - Kurt Bostelaar "Clarify your core message" (WHY->WHAT core message + Convince<->Clarify spectrum)
//   - EU Business School experiential / 7-phase session pedagogy

const COURSE = {
  code: "BARBM312",
  title: "AI in Investment and Business Growth",
  level: "Bachelor · FHEQ Level 6 · Year 3 · 5 ECTS",
  professor: "EU Business School",
  tagline: "Interactive Framework Galleries & Course Materials",
  year: "2026",
};

// Each unit carries everything its pages need.
const UNITS = [
  {
    n: 1,
    slug: "unit1",
    title: "AI, Data & Strategic Business Growth",
    short: "Data, Growth & CX",
    pedagogy: "Guided Discovery",
    pedagogyCode: "GD",
    blurb: "Data, insight and decision-making; customer engagement, experience and personalisation; embedded vs. AI-native products; using AI to spot new market opportunities.",
    // Bostelaar core-message layer
    coreMessage: "Data is only an asset when it becomes a decision — AI turns customer signals into growth.",
    why: "Most firms drown in data yet starve for insight. Growth comes from converting signals into decisions customers can feel.",
    what: "Decision pipelines, engagement loops, personalisation, embedded vs. AI-native product choices, and opportunity sensing.",
    spectrum: 35, // 0 = pure Convince (inspire), 100 = pure Clarify (instruct)
    spectrumNote: "Early unit, mixed audience awareness → lean motivational/Convince to build belief, then clarify the mechanics.",
    // Pre-reading
    preReadTitle: "From Data Exhaust to Decision Advantage",
    preReadSub: "Why most customer data never becomes customer value",
    keyFramework: "The DIKW → Decision Ladder",
    // Case
    caseTitle: "LumaCart — The Personalisation Trap",
    caseSub: "A mid-market retailer chasing growth through AI personalisation",
    // Slibrary thumbnails (Thumbnail Thinking)
    sets: [
      { name: "Set 1 — Data to Decision", frameworks: [
        { t: "DIKW Pyramid", d: "Data → Information → Knowledge → Wisdom" },
        { t: "OODA Loop", d: "Observe → Orient → Decide → Act, at AI speed" },
        { t: "Decision-Intelligence Stack", d: "Signals, models, judgment, action layered for growth" },
        { t: "Data Value Chain", d: "Capture → store → process → analyse → act" },
        { t: "Insight-to-Action Gap", d: "Why analysis rarely changes behaviour" },
      ]},
      { name: "Set 2 — Customer Engagement & CX", frameworks: [
        { t: "Customer Journey Map", d: "End-to-end touchpoints from awareness to advocacy" },
        { t: "Moments of Truth", d: "Carlzon's high-stakes service encounters" },
        { t: "Engagement Flywheel", d: "Attract → engage → delight → repeat" },
        { t: "Personalisation Ladder", d: "Segment → recommend → predict → 1-to-1" },
        { t: "Jobs To Be Done", d: "What the customer hires the product to do" },
      ]},
      { name: "Set 3 — Product Architecture", frameworks: [
        { t: "Embedded vs. AI-Native 2×2", d: "Bolt-on intelligence vs. built-in intelligence" },
        { t: "Build · Buy · Partner", d: "Sourcing the intelligence layer" },
        { t: "Legacy Modernisation Curve", d: "Optimise old systems vs. rebuild" },
        { t: "Value Proposition Canvas", d: "Gains, pains, jobs vs. products & services" },
        { t: "Data Network Effects", d: "More use → more data → better product" },
      ]},
      { name: "Set 4 — Opportunity Sensing", frameworks: [
        { t: "White-Space Map", d: "Unmet needs between existing offers" },
        { t: "Demand-Signal Radar", d: "Reading emerging consumer needs from data" },
        { t: "Blue Ocean Strategy Canvas", d: "Create uncontested market space" },
        { t: "Trend → Opportunity Funnel", d: "From weak signal to validated bet" },
        { t: "Three Horizons", d: "Core, emerging and future growth horizons" },
      ]},
    ],
    // Council of Giants for this unit
    giants: [
      { name: "Russell Ackoff", role: "DIKW Pyramid", lens: "\"A wealth of data creates a poverty of attention.\"" },
      { name: "John Boyd", role: "OODA Loop", lens: "\"Whoever can handle the quickest rate of change survives.\"" },
      { name: "Clayton Christensen", role: "Jobs To Be Done", lens: "\"Customers hire products to do a job.\"" },
      { name: "Jan Carlzon", role: "Moments of Truth", lens: "\"15 seconds decides the whole relationship.\"" },
      { name: "W. Chan Kim & R. Mauborgne", role: "Blue Ocean Strategy", lens: "\"Make the competition irrelevant.\"" },
    ],
  },

  {
    n: 2,
    slug: "unit2",
    title: "The Economics of AI Adoption — Benefits",
    short: "AI Benefits",
    pedagogy: "Live Data Lab",
    pedagogyCode: "DL",
    blurb: "The AI productivity paradox; strategic benefits across functions; internal productivity gains; revenue and customer impact through acquisition and retention.",
    coreMessage: "AI value lags AI investment — benefits are real but arrive on a J-curve, not a switch.",
    why: "Boards expect instant ROI and lose faith in the dip. Naming the lag protects good bets from being killed early.",
    what: "The productivity paradox, function-level benefits, automation gains, and revenue/retention measurement.",
    spectrum: 50,
    spectrumNote: "Skeptical-but-engaged audience → balanced blend: convince that benefits are real, clarify how to measure them.",
    preReadTitle: "The J-Curve of AI Value",
    preReadSub: "Why the payoff comes after the productivity dip",
    keyFramework: "The Solow / Brynjolfsson Productivity J-Curve",
    caseTitle: "Vantix Logistics — Where Did the ROI Go?",
    caseSub: "A freight firm two years into AI with profits flat",
    sets: [
      { name: "Set 5 — The AI Paradox", frameworks: [
        { t: "Productivity J-Curve", d: "Value dips before it climbs" },
        { t: "Solow Paradox Revisited", d: "AI everywhere except the statistics" },
        { t: "Adoption → Impact Lag", d: "Time between deploy and measurable gain" },
        { t: "Intangible Capital Iceberg", d: "Process & skill investment hidden below ROI" },
        { t: "Diffusion S-Curve", d: "Innovators to laggards over time" },
      ]},
      { name: "Set 6 — Functional Benefits", frameworks: [
        { t: "Value-Chain Heatmap", d: "Where AI lifts each activity" },
        { t: "Function Benefit Matrix", d: "Marketing, ops, finance, HR gains mapped" },
        { t: "Automation Potential Grid", d: "Task automatability vs. value" },
        { t: "AI Use-Case Portfolio", d: "Quick wins vs. strategic bets" },
        { t: "Capability Uplift Map", d: "Augmenting human capability per role" },
      ]},
      { name: "Set 7 — Productivity Gains", frameworks: [
        { t: "Cost-to-Serve Curve", d: "Unit cost falling with automation" },
        { t: "Process Cycle Efficiency", d: "Value-add time / total time" },
        { t: "Lean Waste Lens (AI)", d: "Eliminating the eight wastes with AI" },
        { t: "Throughput Accounting", d: "Bottleneck-driven gain measurement" },
        { t: "Effort-Value Reallocation", d: "Freed hours redeployed to high-value work" },
      ]},
      { name: "Set 8 — Revenue & Customers", frameworks: [
        { t: "CAC : LTV Ratio", d: "Acquisition cost vs. lifetime value" },
        { t: "Retention / Churn Cohort", d: "AI lift on customer retention over time" },
        { t: "Pirate Metrics (AARRR)", d: "Acquisition to revenue funnel" },
        { t: "Net Revenue Retention", d: "Expansion minus churn from AI features" },
        { t: "Growth Loop", d: "Output that feeds the next acquisition" },
      ]},
    ],
    giants: [
      { name: "Erik Brynjolfsson", role: "Productivity J-Curve", lens: "\"The benefits lag the investment by years.\"" },
      { name: "Robert Solow", role: "Productivity Paradox", lens: "\"Computers everywhere except the productivity statistics.\"" },
      { name: "Everett Rogers", role: "Diffusion of Innovations", lens: "\"Adoption is a social process, not a switch.\"" },
      { name: "Eliyahu Goldratt", role: "Theory of Constraints", lens: "\"An hour saved off a non-bottleneck is a mirage.\"" },
      { name: "Dave McClure", role: "Pirate Metrics", lens: "\"Measure the funnel, not the vanity.\"" },
    ],
  },

  {
    n: 3,
    slug: "unit3",
    title: "The Economics of AI Adoption — Costs",
    short: "AI Costs",
    pedagogy: "Mini-Hackathon",
    pedagogyCode: "HK",
    blurb: "The AI economy stack; cloud & hosting costs; open-source vs. proprietary LLMs; operational and integration costs; talent scarcity; risk mitigation; the cost-benefit trade-off.",
    coreMessage: "The licence fee is the tip of the iceberg — true AI cost is integration, talent and risk.",
    why: "Business cases die when the hidden 80% of cost surfaces post-launch. Surface it first.",
    what: "The economy stack, infra options, model strategy, integration & talent cost, and risk-adjusted trade-offs.",
    spectrum: 70,
    spectrumNote: "Practitioner audience making budget decisions → lean Clarify/instructional with concrete cost structures.",
    preReadTitle: "The AI Iceberg — What Your Business Case Isn't Telling You",
    preReadSub: "Total cost of ownership for enterprise AI",
    keyFramework: "Total Cost of AI Ownership (TCO-AI)",
    caseTitle: "Helios Health — The €3M Model That Cost €11M",
    caseSub: "A clinic group blindsided by the cost beneath the model",
    sets: [
      { name: "Set 9 — The AI Economy Stack", frameworks: [
        { t: "AI Value Stack", d: "Chips → cloud → models → apps" },
        { t: "Compute Cost Pyramid", d: "Training vs. inference vs. fine-tune" },
        { t: "Token Economics", d: "Cost per token at scale" },
        { t: "Hyperscaler Dependency Map", d: "Concentration and lock-in risk" },
        { t: "Capex vs. Opex Shift", d: "Owning vs. renting intelligence" },
      ]},
      { name: "Set 10 — Infrastructure Choices", frameworks: [
        { t: "Private · Hybrid · Hyperscaler 2×2", d: "Control vs. cost of hosting" },
        { t: "Cloud Cost Waterfall", d: "Where the monthly bill actually goes" },
        { t: "Latency-Cost Frontier", d: "Speed you pay for vs. speed you need" },
        { t: "Data Gravity Map", d: "Compute follows where data lives" },
        { t: "FinOps Loop", d: "Inform → optimise → operate cloud spend" },
      ]},
      { name: "Set 11 — Model & Talent Strategy", frameworks: [
        { t: "Open vs. Proprietary LLM 2×2", d: "Control & cost vs. capability & speed" },
        { t: "Make-vs-Buy Decision Tree", d: "When to fine-tune, when to call an API" },
        { t: "Talent Scarcity Heatmap", d: "Where AI/MLOps skills cost most" },
        { t: "Skill-Premium Curve", d: "Wage premium for scarce AI roles" },
        { t: "MLOps Maturity Ladder", d: "Ad hoc to fully automated pipelines" },
      ]},
      { name: "Set 12 — Risk & Trade-off", frameworks: [
        { t: "Cost-Benefit Trade-off Matrix", d: "Value vs. total risk-adjusted cost" },
        { t: "AI Risk Register", d: "Likelihood × impact × mitigation" },
        { t: "Bias & Failure Modes Map", d: "Where models break and who pays" },
        { t: "Black Swan Radar", d: "Taleb's tail-risk early warning" },
        { t: "Mitigation Cost Curve", d: "Diminishing returns on de-risking" },
      ]},
    ],
    giants: [
      { name: "Nassim Nicholas Taleb", role: "Black Swan / Tail Risk", lens: "\"It is the rare event that ruins you.\"" },
      { name: "Cathy O'Neil", role: "Algorithmic Bias Audit", lens: "\"Models are opinions embedded in maths.\"" },
      { name: "Andrew Ng", role: "MLOps & Data-Centric AI", lens: "\"It's not the model, it's the data and the plumbing.\"" },
      { name: "Roy Schwartz et al.", role: "Green AI vs. Red AI", lens: "\"Efficiency must be a first-class metric.\"" },
      { name: "J.B. Quinn", role: "Strategic Outsourcing", lens: "\"Own the core, rent the rest.\"" },
    ],
  },

  {
    n: 4,
    slug: "unit4",
    title: "IP & Value Creation through AI",
    short: "IP & Value",
    pedagogy: "Moot Court",
    pedagogyCode: "MC",
    blurb: "IP in the age of AI — patent, copyright, trademark; LLM wrappers vs. defensible innovation; data as IP; AI-generated content & code rights; patenting and safeguarding AI.",
    coreMessage: "A wrapper is a feature, not a moat — durable AI value is owned data, defensible IP and switching cost.",
    why: "Investors fund moats, not demos. Students must tell a defensible asset from a thin layer over someone else's model.",
    what: "IP categories under AI, wrapper vs. moat, data as IP, authorship & licensing, and safeguarding innovation.",
    spectrum: 55,
    spectrumNote: "Mixed legal/strategy content → balance: convince why moats matter, clarify the legal mechanics.",
    preReadTitle: "Can AI Be an Author — and Can You Own a Wrapper?",
    preReadSub: "Defensibility and authorship at the AI frontier",
    keyFramework: "The Authorship Decision Tree + Moat Ladder",
    caseTitle: "SynthVerse — Who Owns What the Model Made?",
    caseSub: "A generative-content startup facing an IP reckoning",
    sets: [
      { name: "Set 13 — IP in the Age of AI", frameworks: [
        { t: "IP Quadrant", d: "Patent · copyright · trademark · trade secret" },
        { t: "Authorship Decision Tree", d: "Human, machine or joint authorship?" },
        { t: "Patentability Funnel", d: "Novel · non-obvious · useful filter" },
        { t: "Inventorship Test", d: "Can an AI be named an inventor?" },
        { t: "Trademark Distinctiveness Spectrum", d: "Generic → fanciful marks" },
      ]},
      { name: "Set 14 — Moat vs. Wrapper", frameworks: [
        { t: "Wrapper vs. Moat Ladder", d: "Thin layer to defensible system" },
        { t: "7 Powers", d: "Hamilton Helmer's durable advantages" },
        { t: "Defensibility Matrix", d: "Differentiation × switching cost" },
        { t: "Proprietary Data Flywheel", d: "Data advantage that compounds" },
        { t: "Value Capture Map", d: "Where margin actually accrues" },
      ]},
      { name: "Set 15 — Data as IP", frameworks: [
        { t: "Data Asset Classification", d: "Owned · licensed · public · derived" },
        { t: "Data Rights Stack", d: "Collection → use → licensing rights" },
        { t: "Data Moat Strength", d: "Uniqueness × scale × freshness" },
        { t: "Privacy-Value Frontier", d: "Compliance limits on data value" },
        { t: "Synthetic Data Trade-off", d: "Cheap data vs. real-world fidelity" },
      ]},
      { name: "Set 16 — Safeguarding Innovation", frameworks: [
        { t: "IP Protection Portfolio", d: "Layered patent + secret + brand defence" },
        { t: "Licensing Models Map", d: "Open · permissive · restrictive · proprietary" },
        { t: "Freedom-to-Operate Check", d: "Are you infringing someone else?" },
        { t: "Open-Source Compliance Ladder", d: "Obligations by licence type" },
        { t: "AI Output Ownership Flow", d: "Who owns model-generated code/content" },
      ]},
    ],
    giants: [
      { name: "Jyh-An Lee et al.", role: "Authorship Decision Tree", lens: "\"Authorship requires a human spark.\"" },
      { name: "Hamilton Helmer", role: "7 Powers", lens: "\"Power is the potential to earn persistent returns.\"" },
      { name: "Peter Thiel", role: "Differentiation & Monopoly", lens: "\"Is your product better — or different?\"" },
      { name: "Lawrence Lessig", role: "Code & IP / Licensing", lens: "\"Code is law; licences are choices.\"" },
      { name: "Andrei Hagiu & Julian Wright", role: "Data Network Effects", lens: "\"Data advantage must compound to matter.\"" },
    ],
  },

  {
    n: 5,
    slug: "unit5",
    title: "Agility, Disruption & Rebranding in the Age of AI",
    short: "Agility & Disruption",
    pedagogy: "Role Play",
    pedagogyCode: "RP",
    blurb: "Business agility and AI; rapid response to changing markets; navigating disruption; strategic rebranding as a motor of change.",
    coreMessage: "AI doesn't reward the biggest — it rewards the fastest to re-decide. Agility is the new moat.",
    why: "Incumbents mistake size for safety. The lesson is that responsiveness, not scale, survives disruption.",
    what: "Agility models, disruption navigation, and rebranding as deliberate strategic change.",
    spectrum: 30,
    spectrumNote: "Story-driven, inspirational unit → lean Convince/motivational; clarify frameworks through narrative cases.",
    preReadTitle: "Disrupt the Disruption — Agility as Strategy",
    preReadSub: "Why responsiveness beats scale when markets shift",
    keyFramework: "Disruption S-Curves + OODA at Enterprise Scale",
    caseTitle: "Aurelia & Co. — A Heritage Brand Meets the Algorithm",
    caseSub: "A 90-year-old brand deciding whether to reinvent",
    sets: [
      { name: "Set 17 — Business Agility", frameworks: [
        { t: "OODA Loop (Enterprise)", d: "Decide faster than the market moves" },
        { t: "Cynefin Framework", d: "Match response to problem complexity" },
        { t: "Agile Operating Model", d: "Squads, tribes and fast feedback" },
        { t: "Sense-Respond Loop", d: "Continuous adaptation to signals" },
        { t: "Real Options Lens", d: "Small bets that buy future flexibility" },
      ]},
      { name: "Set 18 — Navigating Disruption", frameworks: [
        { t: "Disruption S-Curves", d: "Incumbent vs. entrant trajectories" },
        { t: "Innovator's Dilemma", d: "Why good firms miss disruption" },
        { t: "Three Horizons of Growth", d: "Defend, build, create simultaneously" },
        { t: "Adjacent Possible Map", d: "Where the next move can realistically go" },
        { t: "Disruption Vulnerability Audit", d: "How exposed is your model?" },
      ]},
      { name: "Set 19 — Strategic Rebranding", frameworks: [
        { t: "Brand Pyramid", d: "Purpose → story → truths → offering" },
        { t: "12 Brand Archetypes", d: "Personality framework for repositioning" },
        { t: "Rebrand Decision Matrix", d: "Refresh vs. reposition vs. rebuild" },
        { t: "StoryBrand Framework", d: "Make the customer the hero" },
        { t: "Brand Equity Bridge", d: "Carrying value across a transition" },
      ]},
      { name: "Set 20 — Change as a Motor", frameworks: [
        { t: "Kotter's 8 Steps", d: "Leading change without losing people" },
        { t: "ADKAR Model", d: "Individual change as the unit of org change" },
        { t: "Burning Platform vs. Burning Ambition", d: "Two motives for change" },
        { t: "Transition Curve", d: "Emotional arc of disruption" },
        { t: "Change Readiness Radar", d: "Is the organisation ready to move?" },
      ]},
    ],
    giants: [
      { name: "John Boyd", role: "OODA Loop", lens: "\"Speed of re-decision wins.\"" },
      { name: "Clayton Christensen", role: "Innovator's Dilemma", lens: "\"Disruption starts at the bottom.\"" },
      { name: "Dave Snowden", role: "Cynefin", lens: "\"Match the response to the kind of problem.\"" },
      { name: "John Kotter", role: "Leading Change", lens: "\"Most change efforts fail for lack of urgency.\"" },
      { name: "Donald Miller", role: "StoryBrand", lens: "\"The customer is the hero, not the brand.\"" },
    ],
  },

  {
    n: 6,
    slug: "unit6",
    title: "Investment Strategies in the AI Era",
    short: "Investment AI",
    pedagogy: "Live Data Lab",
    pedagogyCode: "DL",
    blurb: "Foundational investment principles; disruption of finance through AI/ML; market prediction, risk profiling, diversification; AI-advisors, ML analytics, blockchain instruments; algorithmic & high-frequency trading.",
    coreMessage: "AI changes the speed and the inputs of investing — not the laws of risk and return.",
    why: "Hype suggests AI repeals diversification and risk. Anchoring on timeless principles prevents costly over-belief.",
    what: "Portfolio principles, ML disruption of finance, prediction & risk tooling, robo-advice, and algo/HFT trading.",
    spectrum: 60,
    spectrumNote: "Quantitative, decision-oriented audience → lean Clarify; convince only where AI hype must be tempered.",
    preReadTitle: "Old Laws, New Speed — Investing After AI",
    preReadSub: "What machine learning changes, and what it cannot",
    keyFramework: "Modern Portfolio Theory meets the ML Adoption Curve",
    caseTitle: "Meridian Capital — The Backtest That Lied",
    caseSub: "An asset manager seduced by an overfit model",
    sets: [
      { name: "Set 21 — Investment Foundations", frameworks: [
        { t: "Modern Portfolio Theory", d: "Efficient frontier of risk vs. return" },
        { t: "Risk-Return Spectrum", d: "No return without bearing risk" },
        { t: "Diversification Curve", d: "Falling risk as assets decorrelate" },
        { t: "Capital Asset Pricing Model", d: "Beta and the price of market risk" },
        { t: "Black-Litterman Model", d: "Blending views with market equilibrium" },
      ]},
      { name: "Set 22 — AI Disrupting Finance", frameworks: [
        { t: "Fintech Disruption Map", d: "Where AI re-prices financial services" },
        { t: "ML Adoption Curve (Investing)", d: "Muldowney's stages of ML in asset mgmt" },
        { t: "Robo-Advisory Stack", d: "Profiling → allocation → rebalancing" },
        { t: "Alt-Data Pyramid", d: "Satellite, card, web data as alpha" },
        { t: "Blockchain Instrument Map", d: "Tokenised and smart-contract assets" },
      ]},
      { name: "Set 23 — Prediction & Risk", frameworks: [
        { t: "Fama-French Factors", d: "Size, value and beyond-market returns" },
        { t: "Risk-Profiling Matrix", d: "Capacity × tolerance for risk" },
        { t: "Prediction Machines Lens", d: "AI cheapens prediction, not judgment" },
        { t: "Backtesting Pitfalls Map", d: "Overfitting and look-ahead bias" },
        { t: "Monte Carlo Cone", d: "Distribution of possible outcomes" },
      ]},
      { name: "Set 24 — Algo & HFT", frameworks: [
        { t: "Algo-Trading Pipeline", d: "Signal → execution → monitoring" },
        { t: "Latency Arms Race", d: "Microseconds as competitive edge" },
        { t: "Market Microstructure Map", d: "Order books, spreads and impact" },
        { t: "Flash-Crash Risk Loop", d: "How automation amplifies shocks" },
        { t: "Execution Cost Frontier", d: "Speed vs. slippage trade-off" },
      ]},
    ],
    giants: [
      { name: "Harry Markowitz", role: "Modern Portfolio Theory", lens: "\"Diversification is the only free lunch.\"" },
      { name: "Fischer Black & Robert Litterman", role: "Bayesian Allocation", lens: "\"Start from the market, then add your views.\"" },
      { name: "Eugene Fama & Kenneth French", role: "Multi-Factor Pricing", lens: "\"Returns have more than one source.\"" },
      { name: "Marcos López de Prado", role: "Financial ML", lens: "\"Most backtests are false discoveries.\"" },
      { name: "Agrawal, Gans & Goldfarb", role: "Prediction Machines", lens: "\"AI lowers the cost of prediction.\"" },
    ],
  },

  {
    n: 7,
    slug: "unit7",
    title: "Innovative AI Enterprises — From Unicorns to Industry Leaders",
    short: "Unicorns & Scaling",
    pedagogy: "Business Challenge · Capstone",
    pedagogyCode: "BC",
    blurb: "Valuing AI-first startups; key drivers of growth; vertical vs. platform AI; scaling AI startups to unicorns and beyond.",
    coreMessage: "Unicorn status is the by-product of a defensible, scalable wedge — not the goal itself.",
    why: "Chasing the billion-dollar label produces fragile companies. Durable scaling comes from a sharp wedge that widens.",
    what: "Valuing AI-first firms, growth drivers, vertical vs. platform strategy, and the scaling path to unicorn.",
    spectrum: 40,
    spectrumNote: "Capstone, aspirational + integrative → blend leaning Convince to inspire, integrating every prior unit's frameworks.",
    preReadTitle: "Why Most AI Startups Never Scale",
    preReadSub: "Wedge, moat and the economics of becoming a unicorn",
    keyFramework: "Vertical vs. Platform AI + The Scaling Funnel",
    caseTitle: "Capstone — The €10M Mandate",
    caseSub: "Build the AI-first growth & investment plan, integrating all 7 units",
    sets: [
      { name: "Set 25 — Valuing AI-First Firms", frameworks: [
        { t: "AI Startup Valuation Stack", d: "Team, data, traction, defensibility" },
        { t: "Cost-Structure Lens", d: "Gross margin reality of AI products" },
        { t: "Rule of 40", d: "Growth + profit threshold for SaaS/AI" },
        { t: "Strategic Asset Map", d: "What an acquirer actually pays for" },
        { t: "Investor Expectation Curve", d: "Milestones by funding stage" },
      ]},
      { name: "Set 26 — Growth Drivers", frameworks: [
        { t: "Growth Loops", d: "Self-reinforcing acquisition engines" },
        { t: "Product-Led Growth", d: "The product as the funnel" },
        { t: "Network Effects Map", d: "Direct, indirect and data effects" },
        { t: "T2D3 Trajectory", d: "Triple, triple, double, double, double" },
        { t: "Flywheel Model", d: "Momentum compounding over time" },
      ]},
      { name: "Set 27 — Vertical vs. Platform", frameworks: [
        { t: "Vertical vs. Platform 2×2", d: "Industry depth vs. cross-sector reach" },
        { t: "Wedge-to-Platform Path", d: "Narrow entry, widening expansion" },
        { t: "Category Design Map", d: "Create and own a new category" },
        { t: "TAM-SAM-SOM Funnel", d: "Sizing the addressable market" },
        { t: "Platform vs. Pipe", d: "Orchestrate value vs. produce it" },
      ]},
      { name: "Set 28 — Scaling to Unicorn", frameworks: [
        { t: "The Scaling Funnel", d: "Seed → Series → scale survival rates" },
        { t: "Blitzscaling Lens", d: "Speed over efficiency to win the market" },
        { t: "Stages of Scale", d: "Founders to professional org" },
        { t: "Unicorn Anatomy", d: "Common DNA of $1B+ AI firms" },
        { t: "Beyond Unicorn — Durability", d: "From valuation to lasting advantage" },
      ]},
    ],
    giants: [
      { name: "Peter Thiel", role: "Zero to One / Monopoly", lens: "\"Competition is for losers.\"" },
      { name: "Reid Hoffman", role: "Blitzscaling", lens: "\"Prioritise speed over efficiency to win.\"" },
      { name: "Geoffrey Moore", role: "Crossing the Chasm", lens: "\"Win the beachhead before the mainstream.\"" },
      { name: "Sangeet Choudary", role: "Platform Revolution", lens: "\"Platforms beat pipes.\"" },
      { name: "Sara Blakely", role: "Resilient Builder", lens: "\"Failure is the best classroom.\"" },
    ],
  },
];

if (typeof module !== "undefined") module.exports = { COURSE, UNITS };
